apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-1
  labels:
    app: static-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
        - name: static-website-container
          image: shivsoftapp/static-website:11
          ports:
            - containerPort: 80
